import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HomeScreen from '../components/Home/HomeScreen'
import { useStateValue } from '../StateProvider/StateProvider'
import Login from './login';
import { useEffect } from 'react';
import { auth } from '../firebase/firebase';
import { onAuthStateChanged } from '@firebase/auth';
export default function Home() {
  const [{ user }, dispatch] = useStateValue();
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, userAuth => {
      if (userAuth) {
        dispatch(({
          type: "Login",
          payload: {
            uid: userAuth.uid,
            email: userAuth.email,
          }
        }))
      }
      else {
        dispatch({
          type: "Logout"
        })
      }
    })
    return unsubscribe;
  }, [dispatch])
  return (
    <div className={styles.app} >
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {!user ? <Login /> : (

        <HomeScreen />
      )}

    </div>
  )
}
